### ISSUE TITLE
Fake Temperature

### ISSUE THREAD

**Issue by fredcox** [martinpitt/umockdev#101]
Hi,

I developing one program with temperature cpu read. I need test my program in several virtual machines. Can i create one fake temperature syfs with umockdev in python3?

**Comment by martinpitt** [comment]
You can fake any file in /sys with umockdev easily, yes. I suppose `/sys/devices/virtual/thermal/thermal_zone0/temp` is a good start, of course which particular file you need depends on the program that is reading it. Was that just a general question, or did you run into difficulties with that? In the latter case, do you have some code to look at?

**Comment by fredcox** [comment]
ok thank you
