### ISSUE TITLE
Update build, test, run instructions for new build system

### ISSUE THREAD

**Issue by patrickyeon** [martinpitt/umockdev#133]
As you'd expect, having moved away from autotools means `./configure && make` etc doesn't work. I'm not familiar with either of meson, ninja, nor valac, so please forgive my bumbling through. What has worked for me (Ubuntu 20.04 focal) is
```
sudo apt install meson ninja-build valac libudev-dev libpcap-dev libgudev-1.0-dev gobject-introspection libgirepository1.0-dev
meson build
cd build && ninja
```
There might be other requirements that aren't commonly on peoples' machines but I've already luckily installed. And I wouldn't be surprised that there's an accepted way to use `meson` and `ninja` that isn't that, but it gave me executables.

Hopefully that's enough breadcrumbs for someone else running into this until you've got a chance to update the README.

**Comment by martinpitt** [comment]
Oops, thanks for pointing out! I updated the README accordingly.

**Comment by martinpitt** [comment]
See https://github.com/martinpitt/umockdev#build-test-run
