### ISSUE TITLE
How to build on pi?

### ISSUE THREAD

**Issue by lucaswxp** [martinpitt/umockdev#142]
Hey guys.

I'm running `maven` trying to build it, but it complains I have no `libpcap` installed:

```
Run-time dependency gio-unix-2.0 found: YES 2.68.0
Run-time dependency libudev found: YES 241
Found CMake: /usr/bin/cmake (3.16.3)
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency libpcap found: NO (tried pkgconfig and cmake)

meson.build:50:0: ERROR: Dependency "libpcap" not found, tried pkgconfig and cmake

A full log can be found at /app/umockdev-0.16.2/build/meson-logs/meson-log.txt
```

But `apt-cache show libpcap-dev` shows I have it:

```
Package: libpcap-dev
Source: libpcap
Version: 1.8.1-6
Architecture: armhf
```

I even tried to build libpcap from source (`http://www.tcpdump.org/release/libpcap-1.5.3.tar.gz`), but didn't work either.

Any help on how can I instruct `umockdev` to find `libpcap`?

**Comment by martinpitt** [comment]
So that means that `pkg-config --modversion libpcap` fails even though the package is installed. This is a local configuration problem. Can you try without `$PKG_CONFIG_PATH`?

**Comment by lucaswxp** [comment]
I tried:

```
export PKG_CONFIG_PATH=
meson setup build/
```

Same thing.

Any ideas what may cause this? I managed build libpcap from source, is there any way to point to it? Even if I have to modify the `meson.build` file. Any help is appreciated.

**Comment by martinpitt** [comment]
As I said, you need to install things and set up `$PKG_CONFIG_PATH` to a place where `pkg-config --modversion libpcap` can find them (this is a much faster and more direct test than trying to build umockdev). You really don't have to build libpcap from source unless you want to modify something.
