### ISSUE TITLE
tests/test-umockdev-run.vala:596: checked_remove ("/tmp/.X11-unix/X5") fails

### ISSUE THREAD

**Issue by xypron** [martinpitt/umockdev#208]
Autopkgtests for umockdev 0.17.17-1 fail:
https://autopkgtest.ubuntu.com/results/autopkgtest-mantic/mantic/amd64/u/umockdev/20230506_063930_ece55@/log.gz

```
# DEBUG: test-umockdev-run.vala:595: failed to clean up /tmp/.X5-lock: No such file or directory
not ok /umockdev-run/integration/input-touchpad - FATAL-ERROR: umockdev-utils.vala:16: cannot remove /tmp/.X11-unix/X5: No such file or directory
Bail out!
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
4/7 umockdev / umockdev-run                   FAIL             4.10s   killed by signal 5 SIGTRAP
```

A similar problem was solved by a2953b1122f4 ("test: Allow missing /tmp/.X5-lock files”)

**Comment by martinpitt** [comment]
Hm, so that means the *unix socket* is missing? Does X.org now clean it up by itself? That'd be nice. I'm certainly happy with ignoring the failure if it works otherwise.
