### ISSUE TITLE
Support for Ethernet devices

### ISSUE THREAD

**Issue by vincentbernat** [martinpitt/umockdev#31]
I would be interested in getting Ethernet devices support in umockdev. It would consists in:
- mocking the associated sysfs tree (should already work)
- mocking some ioctl (like ethtool ioctl)
- mocking a dummy ethernet device (appear as a regular ethernet device like the one from dummy driver: a blackhole)

**Comment by discordianfish** [comment]
@vincentbernat Now given up? ;)

**Comment by vincentbernat** [comment]
I didn't even remember that! I didn't make any progress on this. It's unlikely I'll work on this: I have added integration tests instead and make use of Linux network namespaces.

**Comment by martinpitt** [comment]
> I have added integration tests instead and make use of Linux network namespaces.

This is a much better approach IMHO, given how special nework devices are in Linux they don't really fit well with umockdev. So I'm closing this now. Thanks!
