### ISSUE TITLE
No IOCTL recorded when no data read from input fd

### ISSUE THREAD

**Issue by APokorny** [martinpitt/umockdev#44]
If you only execute ioctl on evdev devices and never read any input events from the evdev fd umockdev-record will never dump the ioctl results.

**Comment by martinpitt** [comment]
This works fine for me:

    sudo umockdev-record -i /dev/input/event2=/tmp/e.ioctl evtest /dev/input/event2

(and immediate Control-C). This is the device for my power button and there are no events. This gives me a reasonable `/tmp/e.ioctl`.

Can you please give me more details about which exact commands you ran and what you did exactly?

**Comment by martinpitt** [comment]
Closing as there hasn't been a response in over two years. If you follow up, please reopen. Thanks!
