### ISSUE TITLE
Program not recognized fake device.

### ISSUE THREAD

**Issue by masterkorp** [martinpitt/umockdev#46]
I am trying to record the serial comns for [YATS](https://github.com/masterkorp/yats) but failed to find the fake `/dev/ttyUSB0` device

I got the device with info with

```
umockdev-record /dev/ttyUSB0 > serial_port.umockdev
```

I recorded the serial comunitcation with:

```
umockdev-record -s /dev/ttyUSB0=0.script -- ./yats
```

Disconnect the device and tried to replay the data with:

```
umockdev-run -d ../serial_port.umockdev -s /dev/ttyUSB0=0.script -- ./yats
```

But without any succes. 

Here are the [generated files](http://gohan.masterkorp.net/~masterkorp/yats_umockdev.tar.bz2)

**Comment by masterkorp** [comment]
ping

**Comment by martinpitt** [comment]
Sorry for the late response! What does "But without any success"  expand to, i. e. what exactly did you see? https://github.com/masterkorp/yats is empty, so I can't try this myself. The generated script and umockdev files look reasonable. What does yats do, does it do everything automatically, or does it respond to user interactions? If so, did you do the same actions on replay as on recording?

**Comment by martinpitt** [comment]
Closing as there hasn't been a response in over two years. If you follow up, please reopen. Thanks!
