### ISSUE TITLE
Build failure in 0.11.1

### ISSUE THREAD

**Issue by hadess** [martinpitt/umockdev#76]
Tried to build 0.11.1 in Fedora Rawhide:
```
src/umockdev-record.c: In function 'resolve':
src/umockdev-record.c:354:10: error: called object 'major' is not a function or function pointer
  major = major (_tmp5_);
          ^~~~~
src/umockdev-record.c:325:8: note: declared here
  guint major = 0U;
        ^~~~~
src/umockdev-record.c:357:10: error: called object 'minor' is not a function or function pointer
  minor = minor (_tmp7_);
          ^~~~~
src/umockdev-record.c:328:8: note: declared here
  guint minor = 0U;
        ^~~~~
```

See for full log:
https://kojipkgs.fedoraproject.org//work/tasks/5025/25395025/build.log

**Comment by hadess** [comment]
Builds correctly on Fedora 27, likely a problem with glibc or gcc changes.

**Comment by hadess** [comment]
I have half a fix (rename the variable to major_int/minor_int, so they can't be confused with the function calls), but the generated vala is missing `#include <sys/sysmacros.h>`, which would require adding a new .vapi...

**Comment by martinpitt** [comment]
Indeed, I can easily replicate the build failures in a rawhide mock. I filed https://bugzilla.gnome.org/show_bug.cgi?id=794651 with a small reproducer about the missing `#include` for `sysmacros.h`. I'll add a workaround for now. Once doing that, I also run into issue #75, looking at that now.
