### ISSUE TITLE
umockdev does not actually link to gudev

### ISSUE THREAD

**Issue by EvaSDK** [martinpitt/umockdev#80]
It looks like gudev is only used in unittests and the only reference in the actual lib is in Makefile.am `src_umockdev_run` targets. I suppose this should actually be `UDEV_CFLAGS` and `UDEV_LIBS` there. Would you accept a patch making gudev optional (default autodetected) for unittests ? It would be useful for expressing correct dependencies in Gentoo.

**Comment by martinpitt** [comment]
Indeed umockdev-run doesn't even use libudev, so this can go entirely. Thanks for pointing out! Pushing a fix.

**Comment by EvaSDK** [comment]
Actually, gudev is still mandatory due to PKG_CHECK_MODULES not being wrapped by a configure switch or tweaked to have a non-fatal _action-if-not-found_. Which solution would you prefer ?

**Comment by martinpitt** [comment]
Non-fatal `action-if-not-found` sounds right. Then `Makefile.am` can conditionally build/run test-umockdev.

**Comment by YenBorLin** [comment]
I followed instruction to build umockdev, and these are the commands:
--------------------------------------------------------------------
git clone https://github.com/martinpitt/umockdev.git
cd umockdev
sudo apt install autoconf automake libtool gtk-doc-tools lcov
./autogen.sh
--------------------------------------------------------------------
the error message was given: 
" No package 'gudev-1.0' found "

The autogen.sh script cannot work.
Then, I check the apt repository about gudev,
the libgudev-1.0-0 was installed already and actually there is no gudev package.

May you help me to overcome this issue ?

**Comment by martinpitt** [comment]
@YenBorLin : Until this is fixed, do `apt install libgudev-1.0-dev`.

**Comment by YenBorLin** [comment]
> @YenBorLin : Until this is fixed, do `apt install libgudev-1.0-dev`.

ok, umockdev was compiled successfully.

thank you
