### ISSUE TITLE
Use AX_CODE_COVERAGE in autoconf-archive instead of gnome-common

### ISSUE THREAD

**Issue by rossburton** [martinpitt/umockdev#89]
As per https://mail.gnome.org/archives/commits-list/2014-August/msg08906.html `GNOME_CODE_COVERAGE` is deprecated, and `AX_CODE_COVERAGE` in autoconf-archive should be used.
They're basically identical so ports are trivial, for example see https://mail.gnome.org/archives/commits-list/2014-August/msg08906.html.

**Comment by martinpitt** [comment]
Fixed in https://github.com/martinpitt/umockdev/commit/1f4728e08421b15e8a371837fc5d834fdcc3bf0c . Thanks for your report!

I will do a new upstream release with this RSN.

**Comment by martinpitt** [comment]
Released in 0.13.
